export const SCHEDULE_STATUS = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REFUSED: "REFUSED",
  PROOF_SUBMITTED: "PROOF_SUBMITTED",
  COMPLETED: "COMPLETED",
  INVALIDATED: "INVALIDATED",
  DISPUTED: "DISPUTED",
} as const;

export type ScheduleStatusType = (typeof SCHEDULE_STATUS)[keyof typeof SCHEDULE_STATUS];